CREATE TABLE Users (
	username VARCHAR(50) PRIMARY KEY, 
	password VARCHAR(255) NOT NULL, 
	firstName VARCHAR(50) NOT NULL, 
	lastName VARCHAR(50) NOT NULL, 
	email VARCHAR(100) UNIQUE, 
	phone VARCHAR(20) UNIQUE
);